services:
  jess-bot:
    build: .
    container_name: jessapi_bot
    restart: always
    stdin_open: true 
    tty: true        
    command: tail -f /dev/null 
    volumes:
      - .:/app
      - /app/node_modules
      - ./auth_info:/app/auth_info
    environment:
      - NODE_ENV=development

volumes:
  jess_data: